-- Sample seed data for the event-service schema.
-- Delete rows if you want a clean insert (optional).
-- DELETE FROM ticket_types;
-- DELETE FROM events;

INSERT INTO events (
  id,
  name,
  title,
  banner,
  start_at,
  end_at,
  location,
  status,
  created_at,
  updated_at
)
VALUES
  (
    1,
    'tech_innovators_summit',
    'Tech Innovators Summit 2025',
    'https://cdn.example.com/banners/tech_innovators.png',
    '2025-02-10 09:00:00',
    '2025-02-12 18:00:00',
    'Moscone Center, San Francisco, CA',
    'published',
    NOW(),
    NOW()
  ),
  (
    2,
    'global_music_festival',
    'Global Music Festival',
    'https://cdn.example.com/banners/global_music.png',
    '2025-05-03 12:00:00',
    '2025-05-05 23:00:00',
    'Zilker Park, Austin, TX',
    'published',
    NOW(),
    NOW()
  ),
  (
    3,
    'culinary_experience_weekend',
    'Culinary Experience Weekend',
    'https://cdn.example.com/banners/culinary_weekend.png',
    '2025-03-21 10:00:00',
    '2025-03-23 22:00:00',
    'Navy Pier, Chicago, IL',
    'published',
    NOW(),
    NOW()
  ),
  (
    4,
    'startup_pitch_day',
    'Startup Pitch Day',
    'https://cdn.example.com/banners/pitch_day.png',
    '2025-01-18 08:00:00',
    '2025-01-18 19:00:00',
    'Station F, Paris, France',
    'draft',
    NOW(),
    NOW()
  ),
  (
    5,
    'art_light_installation',
    'Art & Light Installation Night',
    'https://cdn.example.com/banners/art_light.png',
    '2025-04-10 18:00:00',
    '2025-04-10 23:59:59',
    'Gardens by the Bay, Singapore',
    'published',
    NOW(),
    NOW()
  )
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  title = VALUES(title),
  banner = VALUES(banner),
  start_at = VALUES(start_at),
  end_at = VALUES(end_at),
  location = VALUES(location),
  status = VALUES(status),
  updated_at = VALUES(updated_at);

INSERT INTO ticket_types (
  id,
  event_id,
  position,
  name,
  description,
  image_url,
  status,
  qty,
  price,
  currency,
  sale_at,
  sale_end,
  created_at,
  updated_at
)
VALUES
  (
    1,
    1,
    1,
    'General Admission',
    'Full summit access plus recorded sessions.',
    'https://cdn.example.com/tickets/tech_innovators_ga.png',
    'on_sale',
    500,
    35000,
    'USD',
    '2024-12-01 09:00:00',
    '2025-02-09 23:00:00',
    NOW(),
    NOW()
  ),
  (
    2,
    1,
    2,
    'VIP Experience',
    'Reserved seating, backstage meet-and-greet, and VIP lounge.',
    'https://cdn.example.com/tickets/tech_innovators_vip.png',
    'limited',
    75,
    95000,
    'USD',
    '2024-12-01 09:00:00',
    '2025-02-05 17:00:00',
    NOW(),
    NOW()
  ),
  (
    3,
    1,
    3,
    'Student Pass',
    'Discounted access with valid academic ID.',
    'https://cdn.example.com/tickets/tech_innovators_student.png',
    'on_sale',
    150,
    15000,
    'USD',
    '2024-12-15 09:00:00',
    '2025-02-09 23:00:00',
    NOW(),
    NOW()
  ),
  (
    4,
    2,
    1,
    'Weekend Pass',
    'Access to all stages and night shows for three days.',
    'https://cdn.example.com/tickets/music_weekend.png',
    'sold_out',
    1200,
    4200000,
    'VND',
    '2025-01-01 10:00:00',
    '2025-05-02 18:00:00',
    NOW(),
    NOW()
  ),
  (
    5,
    2,
    2,
    'Single Day (Any)',
    'Choose any festival day at entry.',
    'https://cdn.example.com/tickets/music_single_day.png',
    'on_sale',
    900,
    1800000,
    'VND',
    '2025-02-01 10:00:00',
    '2025-05-04 10:00:00',
    NOW(),
    NOW()
  ),
  (
    6,
    3,
    1,
    'Chef''s Table',
    'Interactive cooking session plus curated dinner.',
    'https://cdn.example.com/tickets/culinary_chefs_table.png',
    'limited',
    40,
    52000,
    'USD',
    '2025-01-10 09:00:00',
    '2025-03-20 18:00:00',
    NOW(),
    NOW()
  ),
  (
    7,
    3,
    2,
    'Marketplace Access',
    'Tasting hall and vendor marketplace access.',
    'https://cdn.example.com/tickets/culinary_marketplace.png',
    'on_sale',
    600,
    12000,
    'USD',
    '2025-01-10 09:00:00',
    '2025-03-22 12:00:00',
    NOW(),
    NOW()
  ),
  (
    8,
    4,
    1,
    'Pitch Participant',
    'Includes mentoring sessions and stage slot.',
    'https://cdn.example.com/tickets/pitch_participant.png',
    'draft',
    30,
    0,
    'USD',
    NULL,
    NULL,
    NOW(),
    NOW()
  ),
  (
    9,
    4,
    2,
    'Audience Pass',
    'Watch live pitches and vote for favorites.',
    'https://cdn.example.com/tickets/pitch_audience.png',
    'pending',
    400,
    5000,
    'USD',
    NULL,
    NULL,
    NOW(),
    NOW()
  ),
  (
    10,
    5,
    1,
    'Sunset Entry',
    'General plaza access from 18:00 to 21:00.',
    'https://cdn.example.com/tickets/art_sunset.png',
    'on_sale',
    300,
    850000,
    'VND',
    '2025-02-15 12:00:00',
    '2025-04-10 17:00:00',
    NOW(),
    NOW()
  ),
  (
    11,
    5,
    2,
    'Night Owl',
    'Late-night immersive experience with artist Q&A.',
    'https://cdn.example.com/tickets/art_nightowl.png',
    'on_sale',
    200,
    1100000,
    'VND',
    '2025-02-15 12:00:00',
    '2025-04-10 20:00:00',
    NOW(),
    NOW()
  )
ON DUPLICATE KEY UPDATE
  position = VALUES(position),
  name = VALUES(name),
  description = VALUES(description),
  image_url = VALUES(image_url),
  status = VALUES(status),
  qty = VALUES(qty),
  price = VALUES(price),
  currency = VALUES(currency),
  sale_at = VALUES(sale_at),
  sale_end = VALUES(sale_end),
  updated_at = VALUES(updated_at);
